# Generated by Django 2.1.7 on 2019-03-14 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20190312_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_expired',
        ),
    ]
