# Generated by Django 2.1.7 on 2019-02-27 18:18

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190224_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(default='curitiba', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='state',
            field=models.CharField(default='paraná', max_length=50),
        ),
    ]
